// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using NexusVerde.Infrastructure.Data;

#nullable disable

namespace NexusVerde.Infrastructure.Migrations
{
    [DbContext(typeof(VeterinaryDbContext))]
    [Migration("20260606021150_AddAnaliseImagemAmbiental")]
    partial class AddAnaliseImagemAmbiental
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusVerde.Domain.Entities.AlertaAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnaliseAmbientalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANALISE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_RESOLUCAO");

                    b.Property<string>("Mensagem")
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("MENSAGEM");

                    b.Property<decimal>("NivelRisco")
                        .HasColumnType("NUMBER")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<int>("RegiaoMonitoradaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<bool>("Resolvido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("RESOLVIDO");

                    b.Property<decimal>("TipoAlerta")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TIPO_ALERTA");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AnaliseAmbientalId");

                    b.HasIndex("NivelRisco");

                    b.HasIndex("RegiaoMonitoradaId");

                    b.HasIndex("Resolvido");

                    b.ToTable("TB_ALERTAS_AMBIENTAIS", (string)null);
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.AnaliseAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANALISE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Classificacao")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CLASSIFICACAO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataAnalise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_ANALISE")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<int>("ImagemSatelitalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_IMAGEM");

                    b.Property<decimal?>("NdviMedio")
                        .HasColumnType("NUMBER(10,4)")
                        .HasColumnName("NDVI_MEDIO");

                    b.Property<decimal>("NivelRisco")
                        .HasColumnType("NUMBER")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<decimal?>("PercentualAreaQueimada")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PERCENTUAL_AREA_QUEIMADA");

                    b.Property<decimal?>("PercentualSoloExposto")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PERCENTUAL_SOLO_EXPOSTO");

                    b.Property<decimal?>("PercentualVegetacao")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PERCENTUAL_VEGETACAO");

                    b.Property<string>("Resumo")
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("RESUMO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ImagemSatelitalId")
                        .IsUnique();

                    b.ToTable("TB_ANALISES_AMBIENTAIS", (string)null);
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.AnaliseImagemAmbiental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANALISE_IMAGEM");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaIndefinida")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AREA_INDEFINIDA");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 2, 11, 50, 292, DateTimeKind.Utc).AddTicks(4337))
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("CRIADO_POR");

                    b.Property<DateTime>("DataAnalise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasDefaultValue(new DateTime(2026, 6, 6, 2, 11, 50, 292, DateTimeKind.Utc).AddTicks(794))
                        .HasColumnName("DATA_ANALISE");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasDefaultValue("Baixo")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("NOME_ARQUIVO");

                    b.Property<double>("PercentualAreaIndefinida")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PERCENTUAL_AREA_INDEFINIDA");

                    b.Property<double>("PercentualPossivelQueimada")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PERCENTUAL_POSSIVEL_QUEIMADA");

                    b.Property<double>("PercentualSoloExposto")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PERCENTUAL_SOLO_EXPOSTO");

                    b.Property<double>("PercentualVegetacaoModerada")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PERCENTUAL_VEGETACAO_MODERADA");

                    b.Property<double>("PercentualVegetacaoSaudavel")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PERCENTUAL_VEGETACAO_SAUDAVEL");

                    b.Property<int>("PossivelQueimada")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("POSSIVEL_QUEIMADA");

                    b.Property<int?>("RegiaoMonitoradaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO_MONITORADA");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("RESUMO");

                    b.Property<int>("SoloExposto")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SOLO_EXPOSTO");

                    b.Property<int>("TotalCelulas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTAL_CELULAS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ATUALIZADO_POR");

                    b.Property<int>("VegetacaoModerada")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VEGETACAO_MODERADA");

                    b.Property<int>("VegetacaoSaudavel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VEGETACAO_SAUDAVEL");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoMonitoradaId");

                    b.ToTable("TB_ANALISES_IMAGEM_AMBIENTAL", (string)null);
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.FonteSatelital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FONTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_CADASTRO")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<decimal?>("FrequenciaRevisitaHoras")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("FREQUENCIA_REVISITA_HORAS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("NOME");

                    b.Property<string>("Provedor")
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("PROVEDOR");

                    b.Property<decimal?>("ResolucaoMetros")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("RESOLUCAO_METROS");

                    b.Property<decimal>("Tipo")
                        .HasColumnType("NUMBER")
                        .HasColumnName("TIPO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_FONTES_SATELITAIS", (string)null);
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.HistoricoMonitoramento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_HISTORICO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_REGISTRO")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<decimal?>("NdviAnterior")
                        .HasColumnType("NUMBER(10,4)")
                        .HasColumnName("NDVI_ANTERIOR");

                    b.Property<decimal?>("NdviAtual")
                        .HasColumnType("NUMBER(10,4)")
                        .HasColumnName("NDVI_ATUAL");

                    b.Property<string>("Observacao")
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<int>("RegiaoMonitoradaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal?>("VariacaoNdvi")
                        .HasColumnType("NUMBER(10,4)")
                        .HasColumnName("VARIACAO_NDVI");

                    b.HasKey("Id");

                    b.HasIndex("DataRegistro")
                        .IsDescending();

                    b.HasIndex("RegiaoMonitoradaId");

                    b.ToTable("TB_HISTORICOS_MONITORAMENTO", (string)null);
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.ImagemSatelital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_IMAGEM");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_CADASTRO")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<DateTime>("DataCaptura")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_CAPTURA");

                    b.Property<int>("FonteSatelitalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_FONTE");

                    b.Property<decimal?>("PercentualNuvem")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("PERCENTUAL_NUVEM");

                    b.Property<bool>("Processada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("PROCESSADA");

                    b.Property<int>("RegiaoMonitoradaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("URL_IMAGEM");

                    b.HasKey("Id");

                    b.HasIndex("DataCaptura");

                    b.HasIndex("FonteSatelitalId");

                    b.HasIndex("RegiaoMonitoradaId");

                    b.ToTable("TB_IMAGENS_SATELITAIS", (string)null);
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.RegiaoMonitorada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AreaKm2")
                        .HasColumnType("NUMBER(15,2)")
                        .HasColumnName("AREA_KM2");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVA");

                    b.Property<decimal>("Bioma")
                        .HasColumnType("NUMBER")
                        .HasColumnName("BIOMA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DATA_CADASTRO")
                        .HasDefaultValueSql("SYSTIMESTAMP");

                    b.Property<string>("Estado")
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("ESTADO");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("NUMBER(10,8)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("NUMBER(11,8)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("NOME");

                    b.Property<string>("Pais")
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("PAIS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_REGIOES_MONITORADAS", (string)null);
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.AlertaAmbiental", b =>
                {
                    b.HasOne("NexusVerde.Domain.Entities.AnaliseAmbiental", "AnaliseAmbiental")
                        .WithMany()
                        .HasForeignKey("AnaliseAmbientalId");

                    b.HasOne("NexusVerde.Domain.Entities.RegiaoMonitorada", "RegiaoMonitorada")
                        .WithMany("AlertasAmbientais")
                        .HasForeignKey("RegiaoMonitoradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnaliseAmbiental");

                    b.Navigation("RegiaoMonitorada");
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.AnaliseAmbiental", b =>
                {
                    b.HasOne("NexusVerde.Domain.Entities.ImagemSatelital", "ImagemSatelital")
                        .WithOne("AnaliseAmbiental")
                        .HasForeignKey("NexusVerde.Domain.Entities.AnaliseAmbiental", "ImagemSatelitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImagemSatelital");
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.AnaliseImagemAmbiental", b =>
                {
                    b.HasOne("NexusVerde.Domain.Entities.RegiaoMonitorada", "RegiaoMonitorada")
                        .WithMany("AnalisesImagensambiental")
                        .HasForeignKey("RegiaoMonitoradaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RegiaoMonitorada");
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.HistoricoMonitoramento", b =>
                {
                    b.HasOne("NexusVerde.Domain.Entities.RegiaoMonitorada", "RegiaoMonitorada")
                        .WithMany("Historicos")
                        .HasForeignKey("RegiaoMonitoradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegiaoMonitorada");
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.ImagemSatelital", b =>
                {
                    b.HasOne("NexusVerde.Domain.Entities.FonteSatelital", "FonteSatelital")
                        .WithMany("ImagensSatelitais")
                        .HasForeignKey("FonteSatelitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusVerde.Domain.Entities.RegiaoMonitorada", "RegiaoMonitorada")
                        .WithMany("ImagensSatelitais")
                        .HasForeignKey("RegiaoMonitoradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonteSatelital");

                    b.Navigation("RegiaoMonitorada");
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.FonteSatelital", b =>
                {
                    b.Navigation("ImagensSatelitais");
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.ImagemSatelital", b =>
                {
                    b.Navigation("AnaliseAmbiental");
                });

            modelBuilder.Entity("NexusVerde.Domain.Entities.RegiaoMonitorada", b =>
                {
                    b.Navigation("AlertasAmbientais");

                    b.Navigation("AnalisesImagensambiental");

                    b.Navigation("Historicos");

                    b.Navigation("ImagensSatelitais");
                });
#pragma warning restore 612, 618
        }
    }
}
