@NexusVerde_HostAddress = http://localhost:5170

### Regiões Monitoradas

GET {{NexusVerde_HostAddress}}/api/RegioesMonitoradas
Accept: application/json

### Análises Ambientais

GET {{NexusVerde_HostAddress}}/api/AnalisesAmbientais
Accept: application/json

### Alertas Ambientais

GET {{NexusVerde_HostAddress}}/api/AlertasAmbientais
Accept: application/json

### Fontes Satelitais

GET {{NexusVerde_HostAddress}}/api/FontesSatelitais
Accept: application/json

### Imagens Satelitais

GET {{NexusVerde_HostAddress}}/api/ImagensSatelitais
Accept: application/json

### Histórico de Monitoramento

GET {{NexusVerde_HostAddress}}/api/HistoricoMonitoramento
Accept: application/json
